### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by plemanach** [FIXTradingCommunity/silverflash#18]
Hello,

I cannot build the project, it look it miss the class MessageHeaderDecoder.

Best Regards,

Patrice

**Comment by donmendelson** [comment]
Class org.fixtrading.silverflash.fixp.messages.MessageHeaderDecoder is generated, so it is not a matter of missing from GitHub. It should appear under target/generated-sources after a build.

After running "mvn clean install" I failed to reproduce your problem. Please retry a clean build, and if it is still a problem, provide more information about the error.

**Comment by plemanach** [comment]
Sorry my bad.
